
export default {
  RESERVA: {
    LOAD: {
      ALL: {
        BEGIN: 'DOACAO_RESERVA_LOAD_ALL_BEGIN',
        SUCCESS: 'DOACAO_RESERVA_LOAD_ALL_SUCCESS',
        FAILURE: 'DOACAO_RESERVA_LOAD_ALL_FAILURE'
      },
      BYID: {
        BEGIN: 'DOACAO_RESERVA_BYID_BEGIN',
        SUCCESS: 'DOACAO_RESERVA_BYID_SUCCESS',
        FAILURE: 'DOACAO_RESERVA_BYID_FAILURE'
      }
    },
    ATIVAR: {
      BEGIN: 'DOACAO_RESERVA_ATIVAR_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_ATIVAR_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_ATIVAR_FAILURE'
    },
    DESATIVAR: {
      BEGIN: 'DOACAO_RESERVA_DESATIVAR_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_DESATIVAR_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_DESATIVAR_FAILURE'
    },
    ADD: {
      BEGIN: 'DOACAO_RESERVA_POST_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_POST_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_POST_FAILURE'
    },
    EDIT: {
      BEGIN: 'DOACAO_RESERVA_PUT_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_PUT_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_PUT_FAILURE'
    },
    UPDATE: {
      BEGIN: 'DOACAO_RESERVA_PUT_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_PUT_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_PUT_FAILURE'
    },
    CLIENTE: {
      BEGIN: 'DOACAO_RESERVA_CLIENTE_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_CLIENTE_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_CLIENTE_FAILURE'
    },
    DIA: {
      BEGIN: 'DOACAO_RESERVA_DIA_BEGIN',
      SUCCESS: 'DOACAO_RESERVA_DIA_SUCCESS',
      FAILURE: 'DOACAO_RESERVA_DIA_FAILURE'
    },
    CLEARERROR: 'DOACAO_RESERVA_CLEAR_ERROR',
    CLEARSUCCESS: 'DOACAO_RESERVA_CLEAR_SUCCESS',
    SEMRESERVA: 'DOACAO_RESERVA_NAO_HAVERA_RESERVA'
  }
}
