
export default {
  ANUNCIO: {
    LOAD: {
      ALL: {
        BEGIN: 'DOACAO_ANUNCIO_LOAD_ALL_BEGIN',
        SUCCESS: 'DOACAO_ANUNCIO_LOAD_ALL_SUCCESS',
        FAILURE: 'DOACAO_ANUNCIO_LOAD_ALL_FAILURE'
      },
      DIA: {
        BEGIN: 'DOACAO_ANUNCIO_LOAD_DIA_BEGIN',
        SUCCESS: 'DOACAO_ANUNCIO_LOAD_DIA_SUCCESS',
        FAILURE: 'DOACAO_ANUNCIO_LOAD_DIA_FAILURE'
      }
    },
    ATIVAR: {
      BEGIN: 'DOACAO_ANUNCIO_ATIVAR_BEGIN',
      SUCCESS: 'DOACAO_ANUNCIO_ATIVAR_SUCCESS',
      FAILURE: 'DOACAO_ANUNCIO_ATIVAR_FAILURE'
    },
    DESATIVAR: {
      BEGIN: 'DOACAO_ANUNCIO_DESATIVAR_BEGIN',
      SUCCESS: 'DOACAO_ANUNCIO_DESATIVAR_SUCCESS',
      FAILURE: 'DOACAO_ANUNCIO_DESATIVAR_FAILURE'
    },
    ADD: {
      BEGIN: 'DOACAO_ANUNCIO_POST_BEGIN',
      SUCCESS: 'DOACAO_ANUNCIO_POST_SUCCESS',
      FAILURE: 'DOACAO_ANUNCIO_POST_FAILURE'
    },
    UPDATE: {
      BEGIN: 'DOACAO_ANUNCIO_PUT_BEGIN',
      SUCCESS: 'DOACAO_ANUNCIO_PUT_SUCCESS',
      FAILURE: 'DOACAO_ANUNCIO_PUT_FAILURE'
    },
    BYID: {
      BEGIN: 'DOACAO_ANUNCIO_BYID_BEGIN',
      SUCCESS: 'DOACAO_ANUNCIO_BYID_SUCCESS',
      FAILURE: 'DOACAO_ANUNCIO_BYID_FAILURE'
    },
    CLEARERROR: 'DOACAO_ANUNCIO_CLEAR_ERROR',
    CLEARSUCCESS: 'DOACAO_ANUNCIO_CLEAR_SUCCESS'
  }
}
